---
title: "Milestone5"
author: "Mengxi Tan"
date: "10/18/2019"
output: html_document
---

**#About This Project**

Every year, there are roughly ~1M immigrants coming to the US from various origins and through different admission channels. How are these immigrants fitting in once they are in the US? Is there a certain a certain group that needs particular help in fitting into the American society?

One important metrics for fitting into the American society, is English speaking capability. According to the US census bureau, in 2017, while 91% of all US citizens self-identified as speaking English "very well", the number among all foreigh-born citizens was only 52%.

Would this impairment in English-speaking capability among immigrants differ by origin, channel of admission, or time? This visualization project aims to provide users with a tool to explore this issue, during the time span of 2009 - 2017.

*time span determined by data availability


**#Raw Data Source**

My raw data comes from two sources: 

1. Homeland Security: 
https://www.dhs.gov/immigration-statistics/yearbook

    covering annual immigration count by different characteristics (visa type, country of origin etc.)

2. American Fact Finder(US Census Bureau): https://factfinder.census.gov/faces/nav/jsf/pages/searchresults.xhtml?refresh=t#none

    covering US resident census data(immigration status, english speaking capability, in labor force or not, etc.)
    
Both data sets address the issue of immigrants to US, segmented by country and state of origin. Note that the US Census Bureau data covers all immigrants *living* in US in that particular year, while the Homeland Security data covers immigrants *moving* to US in that year. Therefore, there is strong connection between the two datasets, yet the Homeland Security sample population is only part of the US Census Bureau sample population.

**#Data Storage and Cleaning: for TF only, will not be shown to users**

Homeland Security data are stored under: raw_data > immigration_yearbook

US Census Bureau data are stored under: raw_data > english_speaking_immigrants

Relevant data that may or may not be used later is under: raw_data > parkinglot_4data

All data loading is finished at this stage


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#When installing package data.table, choose "No compliation" method

library(readxl)
library(skimr)
library(ggplot2)
library(readxl)
library(janitor)
library(gifski)
library(gganimate)
library(data.table)
library(png)
library(tidyverse)

#DATA LOADING: Homeland Security Part

#load the immigration by continent data
#clean up names and values

immigration_continent <- read_xlsx("raw_data/immigration_yearbook/Immigration_ByContinent.xlsx", na = c("", "NA")) %>%
  clean_names()

#load the immigration by country data
#clean up names and values
# "-" means 0, D means cannot disclose, will do further wrangling once we are in the anlaysis stage

immigration_country_2017 <- read_xlsx("raw_data/immigration_yearbook/2017_table10d.xlsx", na = c("", "NA")) %>%
  clean_names() %>%
  mutate(year = 2017)

immigration_country_2016 <- read_xlsx("raw_data/immigration_yearbook/2016_table10d.xlsx", na = c("", "NA")) %>%
  clean_names() %>%
  mutate(year = 2016)

immigration_country_2015 <- read_xlsx("raw_data/immigration_yearbook/2015_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2015)

immigration_country_2014 <- read_xlsx("raw_data/immigration_yearbook/2014_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2014)

immigration_country_2013 <- read_xlsx("raw_data/immigration_yearbook/2013_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2013)


immigration_country_2012 <- read_xlsx("raw_data/immigration_yearbook/2012_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2012)

immigration_country_2011 <- read_xlsx("raw_data/immigration_yearbook/2011_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2011)

immigration_country_2010 <- read_xlsx("raw_data/immigration_yearbook/2010_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2010)

immigration_country_2009 <- read_xlsx("raw_data/immigration_yearbook/2009_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2009)


#Combine the country tables together
immigration_country <- rbind(immigration_country_2009,
                             immigration_country_2010,
                             immigration_country_2011,
                             immigration_country_2012,
                             immigration_country_2013,
                             immigration_country_2014,
                             immigration_country_2015,
                             immigration_country_2016,
                             immigration_country_2017)

# skim the consolidated database
skim(immigration_country)

# identified one wrong record from skimming (named "Country" with all NAs)
# drop that row
# note that this table contains rows with both:
#   1) immigration by country by year
#   2) immigration by year, for all country
# will need to separate the two later on in mapping

immigration_country %>% drop_na()

# make a clean data directory
dir.create("clean_data")

#DATA LOADING: US Census Bureau Part
#load english speaking capability by continent

english_by_continent  <- read_xlsx("raw_data/english_speaking_immigrants/english_by_continent.xlsx", na = c("", "NA")) %>% clean_names()

#load english speaking capability by country, for the top 10 country with most US immigrants
english_by_country <-
read_xlsx("raw_data/english_speaking_immigrants/english_by_country.xlsx", na = c("", "NA")) %>% clean_names()

# write the clean data to csv
write.csv(immigration_country, file = "clean_data/immigration_country.csv")
write.csv(immigration_country, file = "clean_data/immigration_continent.csv")
write.csv(english_by_continent, file = "clean_data/english_continent.csv")
write.csv(english_by_country, file = "clean_data/english_country.csv")


```




